var news={
    "data": [{
      title: 'Apple China Supplier Offers $1,800 Bonus To Workers After Over 20,000 Recruits Leave Over Pay Issues - Apple  ( NASDAQ:AAPL ) ',
      url: 'https://www.benzinga.com/news/22/11/29865751/apple-china-supplier-offers-1-800-bonus-to-workers-after-over-20-000-recruits-leave-over-pay-issues',
      time_published: '20221128T034921',
      authors: [Array],
      summary: 'In a bid to sustain the staff levels needed to run the main iPhone-making facility, key Apple Inc. AAPL supplier Foxconn is reportedly offering bonuses of as much as $1,800 to its existing workers after massive protests.',
      banner_image: 'https://cdn.benzinga.com/files/images/story/2022/11/27/shutterstock_1448445746.jpg?width=1200&height=800&fit=crop',   
      source: 'Benzinga',
      category_within_source: 'News',
      source_domain: 'www.benzinga.com',
      topics: [Array],
      overall_sentiment_score: 0.077515,
      overall_sentiment_label: 'Neutral',
      ticker_sentiment: [Array]
    },
    {
      title: 'Augmented Reality and Virtual Reality Market Size to Increase by USD 364557.67 Million: 35% growth to originate from APAC - Technavio',
      url: 'https://www.prnewswire.com/news-releases/augmented-reality-and-virtual-reality-market-size-to-increase-by-usd-364557-67-million-35-growth-to-originate-from-apac---technavio-301687233.html',
      time_published: '20221128T013000',
      authors: [Array],
      summary: 'NEW YORK, Nov. 27, 2022 /PRNewswire/ -- The Augmented Reality and Virtual Reality Market by Technology, Application, and Geography - Forecast and Analysis 2023-2027 report has been published by Technavio.',
      banner_image: 'https://mma.prnewswire.com/media/1955564/Technavio_Global_Augmented_Reality_and_Virtual_Reality_Market_Infographic.jpg?w=500',
      source: 'PR Newswire',
      category_within_source: 'n/a',
      source_domain: 'www.prnewswire.com',
      topics: [Array],
      overall_sentiment_score: 0.28456,
      overall_sentiment_label: 'Somewhat-Bullish',
      ticker_sentiment: [Array]
    },
    {
      title: "Tesla, Amazon, Apple, Lufax And SoFi: Why These 5 Stocks Are Drawing Investors' Attention Today - Tesla  ( NASDAQ:TSLA ) , Amazon.com  ( NASDAQ:AMZN ) ",
      url: 'https://www.benzinga.com/news/22/11/29865717/tesla-amazon-apple-lufax-and-sofi-why-these-5-stocks-are-drawing-investors-attention-today',
      time_published: '20221128T011935',
      authors: [Array],
      summary: 'Wall Street indices closed mixed on Friday with the Nasdaq and the S&P 500 closing in the red while the Dow ended the session higher. Investors and traders balanced the possibilities of a slower rate hike going further and strong retail earnings with concerns of COVID-19 lockdowns and protests in ...',
      banner_image: 'https://cdn.benzinga.com/files/images/story/2022/11/27/shutterstock_2088641623.jpg?width=1200&height=800&fit=crop',   
      source: 'Benzinga',
      category_within_source: 'Markets',
      source_domain: 'www.benzinga.com',
      topics: [Array],
      overall_sentiment_score: -0.081819,
      overall_sentiment_label: 'Neutral',
      ticker_sentiment: [Array]
    },
    {
      title: "Apple Co-Founder Says Many Cryptocurrencies Are 'Rip-Offs' But Only One Is 'Pure Gold' - Bitcoin  ( BTC/USD ) ",
      url: 'https://www.benzinga.com/markets/cryptocurrency/22/03/26011718/apple-co-founder-says-many-cryptocurrencies-are-rip-offs-but-only-one-is-pure-gold-2',
      time_published: '20221127T192500',
      authors: [Array],
      summary: `Apple Inc. AAPL co-founder Steve Wozniak has described Bitcoin BTC/USD as the only cryptocurrency that's "pure-gold mathematics." What Happened: Wozniak made the comments about Bitcoin in an interview with Business Insider, adding that many cryptocurrencies are untrustworthy and have a track ...`,
      banner_image: 'https://cdn.benzinga.com/files/images/story/2012/37411434500_0137b46a26_c.jpg?width=1200&height=800&fit=crop',        
      source: 'Benzinga',
      category_within_source: 'Trading',
      source_domain: 'www.benzinga.com',
      topics: [Array],
      overall_sentiment_score: 0.115644,
      overall_sentiment_label: 'Neutral',
      ticker_sentiment: [Array]
    },
    {
      title: "Shanghai Hit By COVID Protests: Demonstrators Chant 'Xi Jinping Step Down, CCP Step Down' - Apple  ( NASDAQ:AAPL ) ",        
      url: 'https://www.benzinga.com/news/22/11/29865633/shanghai-hit-by-covid-protests-demonstrators-chant-xi-jinping-step-down-ccp-step-down',
      time_published: '20221127T175641',
      authors: [Array],
      summary: "On Sunday, protests spread across Shanghai and Beijing against China's strict 'zero COVID' policies. It's been almost three years since China has followed some of the strictest COVID restrictions in the world.",
      banner_image: 'https://cdn.benzinga.com/files/images/story/2022/11/27/china_covid_shutter.jpg?width=1200&height=800&fit=crop',       
      source: 'Benzinga',
      category_within_source: 'General',
      source_domain: 'www.benzinga.com',
      topics: [Array],
      overall_sentiment_score: -0.202934,
      overall_sentiment_label: 'Somewhat-Bearish',
      ticker_sentiment: [Array]
    },
    {
      title: 'A $1,000 Investment In Apple Just After Thanksgiving Could Be Worth This Much By The End Of The Year - Apple  ( NASDAQ:AAPL ) ',
      url: 'https://www.benzinga.com/general/education/22/11/29865628/a-1-000-investment-in-apple-just-after-thanksgiving-could-be-worth-this-much-by-the-end-of-the-',
      time_published: '20221127T171803',
      authors: [Array],
      summary: "Apple, Inc.'s AAPL stock is down about 16.1% in the year-to-date period. The decline is almost in line with the performance of the broader market, with the S&P 500 Index down about 15.5% during the period. The tech-heavy Nasdaq Composite Index has plunged a steeper 28.2% during the period.",
      banner_image: 'https://cdn.benzinga.com/files/images/story/2022/11/27/apple_dinner.jpg?width=1200&height=800&fit=crop',
      source: 'Benzinga',
      category_within_source: 'General',
      source_domain: 'www.benzinga.com',
      topics: [Array],
      overall_sentiment_score: 0.173613,
      overall_sentiment_label: 'Somewhat-Bullish',
      ticker_sentiment: [Array]
    },
    {
      title: "Steve Jobs Told Zynga In-App Purchases Were 'Stupid.' 15 Years Later, The 'FarmVille' Creator Lands Biggest Video Game Deal Ever - Apple  ( NASDAQ:AAPL ) , Take-Two Interactive  ( NASDAQ:TTWO ) ",
      url: 'https://www.benzinga.com/news/22/01/25005741/steve-jobs-told-zynga-in-app-purchases-were-stupid-15-years-later-the-farmville-creator-lands-bigges-1',
      time_published: '20221127T144800',
      authors: [Array],
      summary: "One of the biggest news items of early 2022 was Take-Two Interactive Software, Inc.'s TTWO $12.7-billion acquisition of Zynga. Zynga founder Mark Pincus shared the story of the company's early days and some lessons along the way.",
      banner_image: 'https://cdn.benzinga.com/files/images/story/2012/t2zynga_0.png?width=1200&height=800&fit=crop',
      source: 'Benzinga',
      category_within_source: 'General',
      source_domain: 'www.benzinga.com',
      topics: [Array],
      overall_sentiment_score: 0.275707,
      overall_sentiment_label: 'Somewhat-Bullish',
      ticker_sentiment: [Array]
    },
    {
      title: '3 Stocks That Could Triple in 3 Years',
      url: 'https://www.fool.com/investing/2022/11/27/3-stocks-that-could-triple-in-3-years/',
      time_published: '20221127T120000',
      authors: [Array],
      summary: 'These companies have multiple ways they could deliver multibagger growth in a relatively short period of time.',
      banner_image: 'https://media.ycharts.com/charts/45a349058065ee7aab212163c62f3218.png',
      source: 'Motley Fool',
      category_within_source: 'n/a',
      source_domain: 'www.fool.com',
      topics: [Array],
      overall_sentiment_score: 0.221841,
      overall_sentiment_label: 'Somewhat-Bullish',
      ticker_sentiment: [Array]
    },
    {
      title: 'US stock market fund with 100% exposure to all the index shares | The Financial Express',
      url: 'https://www.financialexpress.com/investing-abroad/featured-stories/us-stock-market-fund-with-100-exposure-to-all-the-index-shares/2893346/',
      time_published: '20221127T052735',
      authors: [],
      summary: 'US stock market fund with 100% exposure to all the index shares The Financial Express ...',
      banner_image: 'https://www.financialexpress.com/wp-content/uploads/2022/11/16-10.jpg',
      source: 'The Financial Express',
      category_within_source: 'IndustryGoogleRSS',
      source_domain: 'www.financialexpress.com',
      topics: [Array],
      overall_sentiment_score: 0.16781,
      overall_sentiment_label: 'Somewhat-Bullish',
      ticker_sentiment: [Array]
    },
    {
      title: "Barron's Top Weekend Stock Picks: Alibaba, Amazon, Apple And The Quantum Computing Revolution - Bitcoin  ( BTC/USD ) , Apple  ( NASDAQ:AAPL ) ",
      url: 'https://www.benzinga.com/news/large-cap/22/11/29863451/barrons-top-weekend-stock-picks-alibaba-amazon-apple-and-the-quantum-computing-revolution',
      time_published: '20221126T211648',
      authors: [Array],
      summary: `Benzinga reviews this weekend's top stories covered by Barron's, here are the articles investors need to read. "Quantum Computing Will Change the World. How to Play the Stocks," by Eric Savitz, points out that the quantum computing revolution is coming, but only a handful of quantum start-ups ...`,
      banner_image: 'https://cdn.benzinga.com/files/images/story/2022/11/26/newspaper2.jpg?width=1200&height=800&fit=crop',
      source: 'Benzinga',
      category_within_source: 'News',
      source_domain: 'www.benzinga.com',
      topics: [Array],
      overall_sentiment_score: 0.209787,
      overall_sentiment_label: 'Somewhat-Bullish',
      ticker_sentiment: [Array]
    },
    {
      title: "Here's What Elon Musk Plans To Do If Twitter Is Removed From Apple, Google Stores - Alphabet  ( NASDAQ:GOOGL ) , Apple  ( NASDAQ:AAPL ) ",
      url: 'https://www.benzinga.com/news/22/11/29865034/heres-what-elon-musk-plans-to-do-if-twitter-is-removed-from-apple-google-stores', 
      time_published: '20221126T193927',
      authors: [Array],
      summary: "After Twitter CEO Elon Musk floated the idea of providing general amnesty to suspended accounts on Twitter, he is now saying that he would make an alternative phone if Apple Inc AAPL and Alphabet Inc's GOOGL Google decide to remove the social media platform from the App store and Google Play.",
      banner_image: 'https://cdn.benzinga.com/files/images/story/2022/11/26/screenshot_2022-10-29_at_10.30.59_pm.png?width=1200&height=800&fit=crop',
      source: 'Benzinga',
      category_within_source: 'News',
      source_domain: 'www.benzinga.com',
      topics: [Array],
      overall_sentiment_score: 0.004814,
      overall_sentiment_label: 'Neutral',
      ticker_sentiment: [Array]
    },
    {
      title: 'How To Invest Like Warren Buffett: 3 Simple Rules - Apple  ( NASDAQ:AAPL ) , Coca-Cola  ( NYSE:KO ) ',
      url: 'https://www.benzinga.com/trading-ideas/long-ideas/22/01/18344238/how-to-invest-like-warren-buffett-3-simple-rules-1',
      time_published: '20221126T192930',
      authors: [Array],
      summary: 'Warren Buffett is considered one of the greatest investors of all time because of the strong returns the "Oracle of Omaha" has generated for his company Berkshire Hathaway ( NYSE: BRK-A ) ( NYSE: BRK-B ) over the years. Buffett uses a disciplined strategy and has rules in place to ...',
      banner_image: 'https://cdn.benzinga.com/files/images/story/2012/145773787_1_0_1.jpg?width=1200&height=800&fit=crop',
      source: 'Benzinga',
      category_within_source: 'General',
      source_domain: 'www.benzinga.com',
      topics: [Array],
      overall_sentiment_score: 0.222476,
      overall_sentiment_label: 'Somewhat-Bullish',
      ticker_sentiment: [Array]
    },
    {
      title: 'Black Friday online sales top $9 billion in new record',
      url: 'https://www.marketwatch.com/story/black-friday-online-sales-top-9-billion-in-new-record-11669482367',
      time_published: '20221126T170600',
      authors: [Array],
      summary: 'A record $9.12 billion was spent online for Black Friday, Nov. 25, up 2.3% year over year.',
      banner_image: 'https://images.mktw.net/im-673654/social',
      source: 'MarketWatch',
      category_within_source: 'Top Stories',
      source_domain: 'www.marketwatch.com',
      topics: [Array],
      overall_sentiment_score: 0.136393,
      overall_sentiment_label: 'Neutral',
      ticker_sentiment: [Array]
    },
    {
      title: 'Elon Musk Threatens to Build a Phone',
      url: 'https://www.thestreet.com/technology/elon-musk-threatens-to-build-a-phone',
      time_published: '20221126T170000',
      authors: [Array],
      summary: "Tensions between the CEO of Twitter and Apple and Alphabet, the app's distributors, are rising.",
      banner_image: 'https://www.thestreet.com/.image/ar_16:9%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cg_faces:center%2Cq_auto:good%2Cw_620/MTgwOTgyNjA1NjQ1MjI3MzY4/tesla-quick-to-show-support-for-chinas-new-data-collection-rules-after-sharp-decline-in-april-sales.jpg',
      source: 'The Street',
      category_within_source: 'n/a',
      source_domain: 'www.thestreet.com',
      topics: [Array],
      overall_sentiment_score: -0.082657,
      overall_sentiment_label: 'Neutral',
      ticker_sentiment: [Array]
    },
    {
      title: "Macroeconomic Numbers, Walmart Results, and Munger's Opinion of Crypto",
      url: 'https://www.fool.com/investing/2022/11/26/macroeconomic-numbers-walmart-results-and-mungers/',
      time_published: '20221126T153100',
      authors: [Array],
      summary: 'Plus a Motley Fool expert answers questions about Roth IRAs, ETFs, and more.',
      banner_image: 'https://g.foolcdn.com/misc-assets/hp-sa-cumulative-growth-chart.png',
      source: 'Motley Fool',
      category_within_source: 'n/a',
      source_domain: 'www.fool.com',
      topics: [Array],
      overall_sentiment_score: 0.102413,
      overall_sentiment_label: 'Neutral',
      ticker_sentiment: [Array]
    },
    {
      title: "Manchester United Stock Spikes Higher On Report Of Apple's Interest In Buying Soccer Club - Apple  ( NASDAQ:AAPL ) , Manchester United  ( NYSE:MANU ) ",
      url: 'https://www.benzinga.com/news/22/11/29864867/manchester-united-stock-spikes-higher-on-report-of-apples-interest-in-buying-soccer-club',
      time_published: '20221126T152235',
      authors: [Array],
      summary: "Manchester United PLC MANU has announced that the soccer team's owners are weighing a potential sale. The team said it was commencing a process to explore strategic alternatives, including a new investment. On Thursday, it was reported that Apple Inc AAPL is interested in buying the soccer team.",
      banner_image: 'https://cdn.benzinga.com/files/images/story/2022/11/26/screenshot_2022-11-26_at_7.49.05_pm.png?width=1200&height=800&fit=crop',
      source: 'Benzinga',
      category_within_source: 'General',
      source_domain: 'www.benzinga.com',
      topics: [Array],
      overall_sentiment_score: 0.111064,
      overall_sentiment_label: 'Neutral',
      ticker_sentiment: [Array]
    },
    {
      title: 'Black Friday Online Sales Hit Record, But Growth Slim',
      url: 'https://www.investors.com/news/black-friday-online-sales-hit-record-but-growth-slim/',
      time_published: '20221126T145700',
      authors: [Array],
      summary: 'Black Friday online sales hit a record this year, but high inflation, economic uncertainty and ever-longer holiday shopping season kept gains muted vs. 2021. Online sales reached $9.12 billion on Black Friday, Nov. 25, up 2.3% vs. a year earlier, according to Adobe Analytics. Electronics led the ...',
      banner_image: 'https://www.investors.com/wp-content/uploads/2021/04/Stock-onlineshopping-03-adobe.jpg',
      source: 'Investors Business Daily',
      category_within_source: 'n/a',
      source_domain: 'www.investors.com',
      topics: [Array],
      overall_sentiment_score: 0.110028,
      overall_sentiment_label: 'Neutral',
      ticker_sentiment: [Array]
    },
    {
      title: 'Motley Fool Investors Look Back at 2022 and Forward to 2023',
      url: 'https://www.fool.com/investing/2022/11/26/motley-fool-investors-look-back-at-2022-and-forwar/',
      time_published: '20221126T133000',
      authors: [Array],
      summary: "Live from the Hawk & Griffin Pub in Vienna, Virginia... it's Motley Fool Money!",
      banner_image: 'https://g.foolcdn.com/misc-assets/hp-sa-cumulative-growth-chart.png',
      source: 'Motley Fool',
      category_within_source: 'n/a',
      source_domain: 'www.fool.com',
      topics: [Array],
      overall_sentiment_score: 0.102613,
      overall_sentiment_label: 'Neutral',
      ticker_sentiment: [Array]
    },
    {
      title: "Market Rally Strong, But Here's Why You Should Be Cautious",
      url: 'https://www.investors.com/market-trend/stock-market-today/dow-jones-futures-market-rally-strong-why-you-should-be-cautious/',  
      time_published: '20221126T131300',
      authors: [Array],
      summary: 'Dow Jones futures will open Sunday evening, along with S&P 500 futures and Nasdaq futures. The stock market rally had solid gains in the holiday-shortened week. The Dow Jones hit a seven-month high. But the S&P 500 index is coming up to its 200-day moving average, a key resistance area.',
      banner_image: 'https://www.investors.com/wp-content/uploads/2021/08/Stock-racestart-01-adobe.jpg',
      source: 'Investors Business Daily',
      category_within_source: 'n/a',
      source_domain: 'www.investors.com',
      topics: [Array],
      overall_sentiment_score: 0.095523,
      overall_sentiment_label: 'Neutral',
      ticker_sentiment: [Array]
    },
    {
      title: '10 exchange-traded funds to take exposure in US stock market | The Financial Express',
      url: 'https://www.financialexpress.com/investing-abroad/featured-stories/10-exchange-traded-funds-to-take-exposure-in-us-stock-market/2893059/',
      time_published: '20221126T123700',
      authors: [],
      summary: '10 exchange-traded funds to take exposure in US stock market The Financial Express ...',
      banner_image: 'https://www.financialexpress.com/wp-content/uploads/2022/11/6-9.jpg',
      source: 'The Financial Express',
      category_within_source: 'MoneyGoogleRSS',
      source_domain: 'www.financialexpress.com',
      topics: [Array],
      overall_sentiment_score: 0.286792,
      overall_sentiment_label: 'Somewhat-Bullish',
      ticker_sentiment: [Array]
    },
    {
      title: "Louis Armstrong Loved Cannabis And Didn't Care Who Knew It, New Documentary Looks At Jazz Legend's Life And Art - Apple  ( NASDAQ:AAPL ) ",
      url: 'https://www.benzinga.com/markets/cannabis/22/11/29844467/louis-armstrong-loved-cannabis-and-didnt-care-who-knew-it-new-documentary-looks-at-jazz-legends-',
      time_published: '20221125T200912',
      authors: [Array],
      summary: `When Jazz legend and New Orleans native Louis Armstrong died in his sleep on July 6, 1971 in his Queens, NYC home, late CBS broadcaster Walter Cronkite said, "We aren't saying goodbye to Louis tonight, because a man's music does not die with him, certainly not this man's."`,
      banner_image: 'https://cdn.benzinga.com/files/images/story/2022/11/25/c7fec6f9cebe1667ffc6ee96c70c6c04.jpg?width=1200&height=800&fit=crop',
      source: 'Benzinga',
      category_within_source: 'General',
      source_domain: 'www.benzinga.com',
      topics: [Array],
      overall_sentiment_score: 0.065008,
      overall_sentiment_label: 'Neutral',
      ticker_sentiment: [Array]
    },
    {
      title: 'Rally Strong, Stocks Setting Up; Why You Should Be Cautious',
      url: 'https://www.investors.com/market-trend/stock-market-today/dow-jones-hits-7-month-high-stocks-near-buy-points-why-you-should-be-cautious/',
      time_published: '20221125T194700',
      authors: [Array],
      summary: "Dow Jones Hits 7-Month High, Stocks Near Buy Points. Why You Should Be Cautious | Investor's Business Daily Investor's Business Daily ...",
      banner_image: 'https://www.investors.com/wp-content/uploads/2021/08/Stock-racestart-01-adobe.jpg',
      source: 'Investors Business Daily',
      category_within_source: 'n/a',
      source_domain: 'www.investors.com',
      topics: [Array],
      overall_sentiment_score: 0.095522,
      overall_sentiment_label: 'Neutral',
      ticker_sentiment: [Array]
    },
    {
      title: "Apple's iPhone Supply Issues Could Hit Revenue. Why Analysts Say Not to Worry.",
      url: 'https://www.barrons.com/articles/apple-stock-price-iphone-supply-china-51669395559',
      time_published: '20221125T192300',
      authors: [Array],
      summary: "Apple's iPhone Issues Could Hit Revenue. Why Analysts Say Not to Worry. ...",
      banner_image: 'https://images.barrons.com/im-672734/social',
      source: 'Barrons',
      category_within_source: 'n/a',
      source_domain: 'www.barrons.com',
      topics: [Array],
      overall_sentiment_score: -0.23777,
      overall_sentiment_label: 'Somewhat-Bearish',
      ticker_sentiment: [Array]
    },
    {
      title: 'Why Apple Shares Dropped Friday',
      url: 'https://www.fool.com/investing/2022/11/25/why-apple-shares-dropped-friday/',
      time_published: '20221125T181255',
      authors: [Array],
      summary: 'Apple is facing what some would consider a good problem to have.',
      banner_image: 'https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Feditorial%2Fimages%2F710728%2Fholiday-black-friday-words-on-smartphone.jpg&op=resize&w=700',
      source: 'Motley Fool',
      category_within_source: 'n/a',
      source_domain: 'www.fool.com',
      topics: [Array],
      overall_sentiment_score: 0.007224,
      overall_sentiment_label: 'Neutral',
      ticker_sentiment: [Array]
    },
    {
      title: 'Why Manchester United Stock Was Rocketing Higher Again Today',
      url: 'https://www.fool.com/investing/2022/11/25/why-manchester-united-stock-was-rocketing-higher/',
      time_published: '20221125T172741',
      authors: [Array],
      summary: 'The stock continues to rise on talk of a possible buyout.',
      banner_image: 'https://g.foolcdn.com/misc-assets/hp-sa-cumulative-growth-chart.png',
      source: 'Motley Fool',
      category_within_source: 'n/a',
      source_domain: 'www.fool.com',
      topics: [Array],
      overall_sentiment_score: 0.168874,
      overall_sentiment_label: 'Somewhat-Bullish',
      ticker_sentiment: [Array]
    },
    {
      title: "Apple's iPhone Supply Issues Could Hit Revenue. Why Analysts Say Not to Worry.",
      url: 'https://www.barrons.com/articles/apple-iphone-supply-china-51669395559',
      time_published: '20221125T170100',
      authors: [Array],
      summary: "Apple's iPhone Issues Could Hit Revenue. Why Analysts Say Not to Worry. ...",
      banner_image: 'https://images.barrons.com/im-672734/social',
      source: 'Barrons',
      category_within_source: 'n/a',
      source_domain: 'www.barrons.com',
      topics: [Array],
      overall_sentiment_score: -0.23777,
      overall_sentiment_label: 'Somewhat-Bearish',
      ticker_sentiment: [Array]
    },
    {
      title: 'Apple faces more iPhone supply woes on Foxconn unrest',
      url: 'https://www.marketwatch.com/story/apple-faces-more-iphone-supply-woes-on-foxconn-unrest-11669394652',
      time_published: '20221125T164400',
      authors: [Array],
      summary: 'Analyst charts inventories up to 30% below normal in the last week, while reports surface of a further drop in November shipments after Foxconn worker unrest.',
      banner_image: 'https://images.mktw.net/im-673757/social',
      source: 'MarketWatch',
      category_within_source: 'Top Stories',
      source_domain: 'www.marketwatch.com',
      topics: [Array],
      overall_sentiment_score: -0.072514,
      overall_sentiment_label: 'Neutral',
      ticker_sentiment: [Array]
    },
    {
      title: 'Microsoft Facing Antitrust Reviews Over Activision Deal, Teams Integration',
      url: 'https://www.investors.com/news/technology/msft-stock-microsoft-facing-antitrust-reviews/',
      time_published: '20221125T160800',
      authors: [Array],
      summary: "MSFT Stock: Microsoft Facing Antitrust Reviews Investor's Business Daily ...",
      banner_image: 'https://www.investors.com/wp-content/uploads/2020/05/Stock-microsoft-06-company.jpg',
      source: 'Investors Business Daily',
      category_within_source: 'n/a',
      source_domain: 'www.investors.com',
      topics: [Array],
      overall_sentiment_score: -0.15243,
      overall_sentiment_label: 'Somewhat-Bearish',
      ticker_sentiment: [Array]
    },
    {
      title: 'Apple Reveals Its Black Friday through Cyber Monday Deals',
      url: 'https://www.thestreet.com/retailers/apple-reveals-black-friday-cyber-monday-deals',
      time_published: '20221125T160500',
      authors: [Array],
      summary: 'Apple is offering gift cards of varying values when customers purchase a number of specific products during its 2022 early holiday promotions.',
      banner_image: 'https://www.thestreet.com/.image/t_share/MTg2NjUxNjY1ODU0NjM3NzQy/amazon-apple.jpg',
      source: 'The Street',
      category_within_source: 'n/a',
      source_domain: 'www.thestreet.com',
      topics: [Array],
      overall_sentiment_score: 0.408535,
      overall_sentiment_label: 'Bullish',
      ticker_sentiment: [Array]
    },
    {
      title: 'Black Friday Comes: Eyes on Retail Sector as Shoppers Head to Stores Following - Microsoft  ( NASDAQ:MSFT ) , Activision Blizzard  ( NASDAQ:ATVI ) ',
      url: 'https://www.benzinga.com/markets/22/11/29859338/black-friday-comes-eyes-on-retail-sector-as-shoppers-head-to-stores-following',
      time_published: '20221125T160006',
      authors: [Array],
      summary: "( Friday Market Open ) Black Friday is here, putting focus on retailers once again after strong quarterly earnings from many big stores. Will door-busters end up dead as a doornail? Analysts wonder if this year's inflation-battered consumer will pack a punch.", 
      banner_image: 'https://cdn.benzinga.com/files/images/story/2022/11/25/shutterstock_735981943.jpg?width=1200&height=800&fit=crop',    
      source: 'Benzinga',
      category_within_source: 'News',
      source_domain: 'www.benzinga.com',
      topics: [Array],
      overall_sentiment_score: -0.043289,
      overall_sentiment_label: 'Neutral',
      ticker_sentiment: [Array]
    },
    {
      title: "Dow Jones Rises; Big Black Friday Discounts; Tesla, Ford Recalls; Binance's Crypto Bailout",
      url: 'https://www.investors.com/market-trend/stock-market-today/dow-jones-rises-big-black-friday-discounts-tesla-ford-recalls-binances-crypto-bailout/',
      time_published: '20221125T153700',
      authors: [Array],
      summary: "Dow Jones Rises. Big Black Friday Discounts. Tesla, Ford Recalls. Binance's Crypto Bailout Investor's Business Daily ...", 
      banner_image: 'https://www.investors.com/wp-content/uploads/2022/03/Stock-applelogocart-01-adobe.jpg',
      source: 'Investors Business Daily',
      category_within_source: 'n/a',
      source_domain: 'www.investors.com',
      topics: [Array],
      overall_sentiment_score: -0.014513,
      overall_sentiment_label: 'Neutral',
      ticker_sentiment: [Array]
    },
    {
      title: '4 ETFs That Are the Best Deals on Black Friday Bonanza',
      url: 'https://www.zacks.com/stock/news/2022386/4-etfs-that-are-the-best-deals-on-black-friday-bonanza',
      time_published: '20221125T151500',
      authors: [Array],
      summary: 'Retailers are splurging on early promotions and discounts as well as free shipping on online purchases to lure customers.The attractive offers would boost retail sales and lead to a surge in stock prices in the days to follow.',
      banner_image: 'https://staticx-tuner.zacks.com/images/default_article_images/default248.jpg',
      source: 'Zacks Commentary',
      category_within_source: 'n/a',
      source_domain: 'www.zacks.com',
      topics: [Array],
      overall_sentiment_score: 0.161323,
      overall_sentiment_label: 'Somewhat-Bullish',
      ticker_sentiment: [Array]
    },
    {
      title: "These 2 Stocks Were on Big Shoppers' Lists on Black Friday",
      url: 'https://www.fool.com/investing/2022/11/25/these-2-stocks-big-shoppers-lists-on-black-friday/',
      time_published: '20221125T141841',
      authors: [Array],
      summary: 'Buying interest is coming from some interesting corners.',
      banner_image: 'https://g.foolcdn.com/misc-assets/hp-sa-cumulative-growth-chart.png',
      source: 'Motley Fool',
      category_within_source: 'n/a',
      source_domain: 'www.fool.com',
      topics: [Array],
      overall_sentiment_score: 0.185157,
      overall_sentiment_label: 'Somewhat-Bullish',
      ticker_sentiment: [Array]
    },
    {
      title: "Apple Analyst's 9 Gift Recommendations For 2022 Holiday Season; Tesla's $30K EV And 2 More Items In 2023 Wishlist - SPDR S&P Retail ETF  ( ARCA:XRT ) ",
      url: 'https://www.benzinga.com/analyst-ratings/analyst-color/22/11/29855083/apple-analysts-9-gift-recommendations-for-2022-holiday-season-teslas-30k-ev-and-2-m',
      time_published: '20221125T140537',
      authors: [Array],
      summary: 'Even in the face of uncertainties, consumers continue to be resilient, estimates by retail industry bodies show.',
      banner_image: 'https://cdn.benzinga.com/files/images/story/2022/11/25/holiday_gifts_photo_by_oatawa_on_shutterstock.jpg?width=1200&height=800&fit=crop',
      source: 'Benzinga',
      category_within_source: 'General',
      source_domain: 'www.benzinga.com',
      topics: [Array],
      overall_sentiment_score: 0.303491,
      overall_sentiment_label: 'Somewhat-Bullish',
      ticker_sentiment: [Array]
    },
    {
      title: 'Apple Supplier Loses Workers After Violent Protests, Cardano Stablecoin Project Shuts Down Over Uncertainty, Tesla & Ford Recall Vehicles: Top Stories Friday, Nov. 25 - Cardano  ( ADA/USD ) , Bitcoin  ( BTC/USD ) ',
      url: 'https://www.benzinga.com/markets/cryptocurrency/22/11/29857639/apple-supplier-loses-workers-after-violent-protests-cardano-stablecoin-project-shuts-down-',
      time_published: '20221125T135751',
      authors: [Array],
      summary: 'Adidas AG ( OTC: ADDYY ) ADDDF initiated a probe against Kanye West into allegations of inappropriate behavior after receiving an anonymous letter making several allegations.',
      banner_image: 'https://cdn.benzinga.com/files/images/story/2022/11/25/union-_image_by_use_at_your_ease_from_pixabay_-.png?width=1200&height=800&fit=crop',
      source: 'Benzinga',
      category_within_source: 'News',
      source_domain: 'www.benzinga.com',
      topics: [Array],
      overall_sentiment_score: -0.052364,
      overall_sentiment_label: 'Neutral',
      ticker_sentiment: [Array]
    },
    {
      title: 'Stock Market Today: Stocks Mixed With Dollar, Black Friday Sales In Focus',
      url: 'https://www.thestreet.com/markets/stock-market-today-stocks-mixed-with-dollar-black-friday-in-focus',
      time_published: '20221125T135400',
      authors: [Array],
      summary: "Stocks are likely to tread water in today's holiday-shortened session as investors look for clues on consumer health from Black Friday sales while eyeing movements in the U.S. dollar.",
      banner_image: 'https://www.thestreet.com/.image/ar_16:9%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cg_faces:center%2Cq_auto:good%2Cw_620/MTkzOTU1MDU5OTA0NTU0NTAx/thumb-unemployment-earnings-js-112322.jpg',
      source: 'The Street',
      category_within_source: 'n/a',
      source_domain: 'www.thestreet.com',
      topics: [Array],
      overall_sentiment_score: 0.009637,
      overall_sentiment_label: 'Neutral',
      ticker_sentiment: [Array]
    },
    {
      title: 'Futures Mixed To Close Out The Week',
      url: 'https://www.investors.com/market-trend/stock-market-today/dow-jones-futures-rise-to-close-out-the-week-tesla-to-recall-about-80000-cars-in-china/',
      time_published: '20221125T131500',
      authors: [Array],
      summary: "Dow Jones Futures Rise To Close Out The Week. Tesla To Recall About 80,000 Cars In China Investor's Business Daily ...",   
      banner_image: 'https://www.investors.com/wp-content/uploads/2021/09/Stock-wallstreetflag-01-adobe.jpg',
      source: 'Investors Business Daily',
      category_within_source: 'n/a',
      source_domain: 'www.investors.com',
      topics: [Array],
      overall_sentiment_score: 0.132779,
      overall_sentiment_label: 'Neutral',
      ticker_sentiment: [Array]
    },
    {
      title: 'US Stocks: Futures largely subdued with Black Friday sales in focus | The Financial Express',
      url: 'https://www.financialexpress.com/market/us-stocks-futures-largely-subdued-with-black-friday-sales-in-focus/2892268/',
      time_published: '20221125T131348',
      authors: [],
      summary: 'US Stocks: Futures largely subdued with Black Friday sales in focus The Financial Express ...',
      banner_image: 'https://www.financialexpress.com/wp-content/uploads/2022/11/1-443.jpg',
      source: 'The Financial Express',
      category_within_source: 'MarketsGoogleRSS',
      source_domain: 'www.financialexpress.com',
      topics: [Array],
      overall_sentiment_score: -0.058029,
      overall_sentiment_label: 'Neutral',
      ticker_sentiment: [Array]
    },
    {
      title: 'Insiders Shed Apple, Amazon And This Retail Exposure - Apple  ( NASDAQ:AAPL ) , Amazon.com  ( NASDAQ:AMZN ) ',
      url: 'https://www.benzinga.com/news/22/11/29857129/insiders-shed-apple-amazon-and-this-retail-exposure',
      time_published: '20221125T130147',
      authors: [Array],
      summary: "The Dow Jones jumped by around 100 points on Wednesday. Investors, meanwhile, focused on some notable insider trades. When insiders sell shares, it indicates their concern in the company's prospects or that they view the stock as being overpriced. Either way, this signals an opportunity to go ...",
      banner_image: 'https://cdn.benzinga.com/files/images/story/2022/11/25/image-apple.png?width=1200&height=800&fit=crop',
      source: 'Benzinga',
      category_within_source: 'Trading',
      source_domain: 'www.benzinga.com',
      topics: [Array],
      overall_sentiment_score: 0.048008,
      overall_sentiment_label: 'Neutral',
      ticker_sentiment: [Array]
    },
    {
      title: 'Futures largely subdued with Black Friday sales in focus',
      url: 'https://www.reuters.com/markets/us/futures-largely-subdued-with-black-friday-sales-focus-2022-11-25/',
      time_published: '20221125T125300',
      authors: [Array],
      summary: 'Nov 25 ( Reuters ) - U.S. stock index futures were largely subdued on Friday, with investors closely monitoring the major retailers as Black Friday sales began against the backdrop of stubbornly high inflation and worries about a potential recession next year.',
      banner_image: 'https://cloudfront-us-east-2.images.arcpublishing.com/reuters/UMCLM7GIGBJEBICL6V5SLQ6NQA.jpg',
      source: 'Reuters',
      category_within_source: 'Markets',
      source_domain: 'www.reuters.com',
      topics: [Array],
      overall_sentiment_score: -0.057996,
      overall_sentiment_label: 'Neutral',
      ticker_sentiment: [Array]
    },
    {
      title: 'Zacks Market Edge Highlights: The Walt Disney, Sony, Apple, Alphabet and Tesla',
      url: 'https://www.zacks.com/stock/news/2022217/zacks-market-edge-highlights-the-walt-disney-sony-apple-alphabet-and-tesla',
      time_published: '20221125T124900',
      authors: [Array],
      summary: 'The Walt Disney, Sony, Apple, Alphabet and Tesla are part of the Zacks Market Edge blog.',
      banner_image: 'https://staticx-tuner.zacks.com/images/articles/main/b9/441.jpg',
      source: 'Zacks Commentary',
      category_within_source: 'n/a',
      source_domain: 'www.zacks.com',
      topics: [Array],
      overall_sentiment_score: 0.158302,
      overall_sentiment_label: 'Somewhat-Bullish',
      ticker_sentiment: [Array]
    },
    {
      title: 'Tesla Analyst Weighs In On 3 Events That Could Set Off A Bull Market Rally In 2023 - SPDR S&P 500  ( ARCA:SPY ) ',
      url: 'https://www.benzinga.com/analyst-ratings/analyst-color/22/11/29855256/tesla-analyst-weighs-in-on-3-events-that-could-set-off-a-bull-market-rally-in-2023',
      time_published: '20221125T120234',
      authors: [Array],
      summary: 'The stock market has been locked in a lackluster phase ever since the start of the year. And the few-and-far-between upsides have proved to be bear market rallies and not those signaling a sustainable uptrend. What Happened: Against this backdrop, a prominent Tesla Inc.',
      banner_image: 'https://cdn.benzinga.com/files/images/story/2022/11/25/bull_market_photo_by_alex_hinds_on_shutterstock.jpg?width=1200&height=800&fit=crop',
      source: 'Benzinga',
      category_within_source: 'General',
      source_domain: 'www.benzinga.com',
      topics: [Array],
      overall_sentiment_score: -0.069548,
      overall_sentiment_label: 'Neutral',
      ticker_sentiment: [Array]
    },
    {
      title: 'Stocks Higher, Apple, Activision, Ford, Black Friday - Five Things To Know',
      url: 'https://www.thestreet.com/markets/stocks-up-apple-activision-ford-black-friday-5-things-to-know',
      time_published: '20221125T115400',
      authors: [Array],
      summary: 'Stock futures edge higher, dollar extends retreat. Apple slips amid reports of more disruption at iPhone factory in China. Activision slumps on concerns over FTC challenge to Microsoft deal. Ford edges lower after recalling 634,000 SUVs and Black Friday expected to see millions return to ...',
      banner_image: 'https://www.thestreet.com/.image/ar_16:9%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cg_faces:center%2Cq_auto:good%2Cw_620/MTkzOTU1MDU5OTA0NTU0NTAx/thumb-unemployment-earnings-js-112322.jpg',
      source: 'The Street',
      category_within_source: 'n/a',
      source_domain: 'www.thestreet.com',
      topics: [Array],
      overall_sentiment_score: 0.031497,
      overall_sentiment_label: 'Neutral',
      ticker_sentiment: [Array]
    },
    {
      title: "Bear markets come in three stages; and we've only just started the second, says veteran analyst.",
      url: 'https://www.marketwatch.com/story/bear-markets-come-in-three-stages-and-weve-only-just-started-the-second-says-veteran-analyst-11669376879',
      time_published: '20221125T114800',
      authors: [Array],
      summary: "There are opportunities in safer bonds and gold, but big tech's days of outperforming are over for now.",
      banner_image: 'https://images.mktw.net/im-673537?width=700&height=491',
      source: 'MarketWatch',
      category_within_source: 'Top Stories',
      source_domain: 'www.marketwatch.com',
      topics: [Array],
      overall_sentiment_score: 0.142451,
      overall_sentiment_label: 'Neutral',
      ticker_sentiment: [Array]
    },
    {
      title: 'Should Invesco S&P 500 Top 50 ETF  ( XLG )  Be on Your Investing Radar?',
      url: 'https://www.zacks.com/stock/news/2022182/should-invesco-sp-500-top-50-etf-xlg-be-on-your-investing-radar',
      time_published: '20221125T112008',
      authors: [Array],
      summary: 'Style Box ETF report for ...',
      banner_image: 'https://staticx-tuner.zacks.com/images/default_article_images/default35.jpg',
      source: 'Zacks Commentary',
      category_within_source: 'n/a',
      source_domain: 'www.zacks.com',
      topics: [Array],
      overall_sentiment_score: 0.18937,
      overall_sentiment_label: 'Somewhat-Bullish',
      ticker_sentiment: [Array]
    },
    {
      title: 'Should iShares Russell Top 200 Growth ETF  ( IWY )  Be on Your Investing Radar?',
      url: 'https://www.zacks.com/stock/news/2022184/should-ishares-russell-top-200-growth-etf-iwy-be-on-your-investing-radar',
      time_published: '20221125T112007',
      authors: [Array],
      summary: 'Style Box ETF report for ...',
      banner_image: 'https://staticx-tuner.zacks.com/images/default_article_images/default323.jpg',
      source: 'Zacks Commentary',
      category_within_source: 'n/a',
      source_domain: 'www.zacks.com',
      topics: [Array],
      overall_sentiment_score: 0.249675,
      overall_sentiment_label: 'Somewhat-Bullish',
      ticker_sentiment: [Array]
    },
    {
      title: 'Should iShares Core S&P 500 ETF  ( IVV )  Be on Your Investing Radar?',
      url: 'https://www.zacks.com/stock/news/2022189/should-ishares-core-sp-500-etf-ivv-be-on-your-investing-radar',
      time_published: '20221125T112005',
      authors: [Array],
      summary: 'Style Box ETF report for ...',
      banner_image: 'https://staticx-tuner.zacks.com/images/default_article_images/default280.jpg',
      source: 'Zacks Commentary',
      category_within_source: 'n/a',
      source_domain: 'www.zacks.com',
      topics: [Array],
      overall_sentiment_score: 0.147981,
      overall_sentiment_label: 'Neutral',
      ticker_sentiment: [Array]
    },
    {
      title: 'Should You Invest in the iShares Expanded Tech Sector ETF  ( IGM ) ?',
      url: 'https://www.zacks.com/stock/news/2022190/should-you-invest-in-the-ishares-expanded-tech-sector-etf-igm',
      time_published: '20221125T112005',
      authors: [Array],
      summary: 'Sector ETF report for ...',
      banner_image: 'https://staticx-tuner.zacks.com/images/default_article_images/default45.jpg',
      source: 'Zacks Commentary',
      category_within_source: 'n/a',
      source_domain: 'www.zacks.com',
      topics: [Array],
      overall_sentiment_score: 0.119779,
      overall_sentiment_label: 'Neutral',
      ticker_sentiment: [Array]
    },
    {
      title: "Apple May Or Mayn't Buy Manchester United - But Fans Are Going Gaga Already - Alphabet  ( NASDAQ:GOOG ) ",
      url: 'https://www.benzinga.com/news/22/11/29855191/apple-may-or-maynt-buy-manchester-united-but-fans-are-going-gaga-already',        
      time_published: '20221125T111511',
      authors: [Array],
      summary: "Apple Inc.'s AAPL CEO Tim Cook reportedly wants to buy the Manchester United football club and fans cannot be happier about it - but is there more to the story? What Happened: The Cupertino-based tech giant is interested in buying Premier League club Manchester United at a whopping £5.8billion, ...",
      banner_image: 'https://cdn.benzinga.com/files/images/story/2022/11/25/manu_photo_by_tatohra_on_shutterstock.jpg?width=1200&height=800'},
    ],
    "pagination": {
      "count": 50,
      "limit": 50,
      "offset": 50,
      "total":50
    }
  }
export default news;